trigger:
- master

pool:
  'My_local_host_agent'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: 'Release'

steps:



- task: BuildInstaller@1
  inputs:
    installTaskMode: 'solution'
    SlnPath: '**/*sln'
    VsVersion: 'VS2019'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'Calculator'

- task: DownloadBuildArtifacts@0
  inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)'
